### ISSUE TITLE
Mobile API

### ISSUE THREAD

**Issue by kevindoveton** [Malvineous/commsecjs#1]
Hello! 

I've just done a bit of research in to the commsec app using a mitm proxy and there is a great versioned api (even documented) that you could use rather than relying on the website to not change. 

Just thought I would let you know in case you wanted to further extend this.

**Comment by Malvineous** [comment]
That would be much more useful, do you have any links?

**Comment by kevindoveton** [comment]
I have only spent about 5 minutes looking into this but here is what I have found. 

https://app.commsec.com.au/v5/services/service.svc/ is the base url for all requests. You can do things such as /watchlist and /getstockinfo

[This zip file](https://github.com/Malvineous/commsecjs/files/2037831/help.html.zip) contains a formatted version of the rss feed found [here](https://app.commsec.com.au/v5/services/service.svc/help)

That's everything i've done but I imagine with a bit more digging you should be able to find lots more.

**Comment by Malvineous** [comment]
I've finally started looking at this, however some of the documentation is lacking.  Do you have any idea how the `Login` or `SSOLogin` API calls work?  I can see they are POST but there's no explanation of how you're supposed to format the request body.

**Comment by Malvineous** [comment]
Managed to intercept the HTTPS traffic with `mitmproxy`, and found the data to the login function is a double JSON-encoded string:

```
let body = JSON.stringify({
	data: JSON.stringify({
		"clientId": "12345",
		"deviceId": "xyz123",
		"devicePlatform": "android",
		"loginType": "pin",
		"password": "1234",
	}),
});
```

I'm able to log in and retrieve a watchlist now.

**Comment by Malvineous** [comment]
Closing this now as I have just pushed an update that uses the mobile API.  Many thanks for pointing out the - in hindsight rather obvious - better solution of using the mobile API!

**Comment by kevindoveton** [comment]
good to hear!
