### ISSUE TITLE
Need help with constructing API request

### ISSUE THREAD

**Issue by Veruso** [Malvineous/commsecjs#3]
I am trying to construct an API request for account holdings,
```dart
http.get(
  'https://app.commsec.com.au/v5/services/service.svc/getholdings?accountId=***',
  headers: {
    'Content-Type': 'application/json',
    'Origin': 'https://app.commsec.com.au',
  },
);
```
However, I receive the following response from the server:
```JSON
{"message":"you need to be authenticated!","messages":null,"requestToken":null,"status":"fail"}
```

I am able to login, receiving `status: success`, along with various tokens:
https://pastebin.com/VMN0rsHj

Could you verify if the `getholdings` endpoint is still valid?

**Comment by Malvineous** [comment]
You need to call the functions provided by the library, it won't work if you make the HTTP calls yourself as the cookies won't be carried across from the library's auth calls to your own.

**Comment by Veruso** [comment]
Is it possible for me to recreate authentication without JavaScript? I am attempting to port this library to a different language.
Also thanks for making this software as it has been helpful to me.

Upon further inspection I have found the source of my problems. I see you are using node-fetch which has cookie processing built-in. Unless I am mistaken, I will also need to generate my own cookies in order for my login post to authenticate the `getholdings` call.

**Comment by Malvineous** [comment]
Ah sorry I misunderstood.  Yes you can recreate it but you will need to ensure your HTTP library maintains cookies between calls.  The cookies are set upon login in the return from the auth call, and need to be passed to all future calls.
